sudo: required
dist: precise
language: php
php:
  - 7.1
  - 7.2
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
before_script:
  - composer self-update
  - composer install
script:
  - vendor/bin/phpunit ./tests