sudo: required
dist: trusty
language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
matrix:
  fast_finish: true
before_script:
  - composer self-update
  - composer install
script:
  - vendor/bin/phpunit ./tests