sudo: required
dist: trusty
language: php
php:
  - 7.1
  - 7.2
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
before_script:
  - composer install
script:
  - vendor/bin/phpunit ./tests